"""empty message

Revision ID: 2643261ad9c8
Revises: f4052f6cc66a
Create Date: 2019-05-12 16:47:26.994087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2643261ad9c8'
down_revision = 'f4052f6cc66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validity', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validity')
    # ### end Alembic commands ###
